Posts.com : Milestone : Views
ahmed025566/posts.com pull request #6
Opened 2023-11-01 20:22 UTC by ahmed025566

Hello there, code reviewer.
Hope you are doing well.

In this milestone you could see that I have done the following: 

- I have added some necessary data to my controllers in order to use them in the views.
- I have added index and show templates for both user and post according to the provided wire frame.

2023-11-01 21:02 UTC, Omar-Muhamad requested changes
# Changes Required ♻️
### Hi @ahmed025566,

### Nice job, you are almost there.

![giphy (2)](https://user-images.githubusercontent.com/68796232/223284713-d4ea97f0-5ad2-438b-8ac5-1481a991da3f.gif)

## (Highlights) Good Points: :+1:
- Your work is well documented. ✔
- The correct workflow is used.  ✔
- All linters checks are ok. ✔

## (Changes Required) Aspects to improve: ♻️

- [ ] Please check the inline comments below ⬇️.

## [Optional] suggestions:

- [ ] Please check the inline comments below ⬇️.

_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

**Cheers and Happy coding!👏👏👏**

Feel free to leave any questions or comments in the PR thread if something is not 100% clear, and please remember to tag me in your question so I can receive the notification**

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-11-01 21:02 UTC, omar-muhamad commented on app/views/users/show.html.erb
> +    <div class= "post">
- [ ] As per this [requirement](https://github.com/microverseinc/curriculum-rails/blob/main/blog-app/projects/Views_project.md#:~:text=page%20to%20another-,Use%20methods%20that%20you%20have%20created%20in%20the%20Blog%20App%20%2D%20processing%20data%20in%20models.,-Hint%3A%20In), Please use the `recent_posts` method here instead of rendering all posts.

[Hint] It will be like that:
```ruby
<% @posts.recent_post.each do |post| %>
-------------
```

2023-11-01 21:02 UTC, omar-muhamad commented on app/views/users/show.html.erb
> +
- [ ] [Optional] It would be better professionally if you make this button like this instead:
```ruby
<button>
  <%= link_to 'See all Post', user_posts_path(@user) %>
</button>
```

2023-11-01 21:02 UTC, omar-muhamad commented on app/views/posts/index.html.erb
> +    <a href="/users/<%= @user.id%>/posts/<%= post.id %>" class="postDetails">
- [ ] [Optional] Because Rails uses Routes it would be better if you used the [link_to](https://www.rubyguides.com/2019/05/rails-link_to-method/) method instead of the regular anchor tag `<a>`.

2023-11-02 20:29 UTC, binhussen approved these changes
Hi @ahmed025566 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉
![IApproveSimonCowellGIF (6)](https://github.com/ahmed025566/posts.com/assets/52010789/0059c146-515b-4446-9d31-773fec024428)

## Highlights
- Added view for app✔️
- Well Stractured Code ✔️
- Used Git flow ✔️
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-11-02 20:44 UTC, merged